"""The detection theory, and its verification by simulation.

A window of ``n`` samples is generated by one of two laws; the Bayes rule picks
the smaller residual sum. With gap ``g = f_j - f_k`` and ``D_n = sum_t g(x_t)^2``
the error conditional on the design is exactly ``Q(sqrt(D_n) / 2 sigma)``. The
population approximation ``Q(sqrt(n rho) / 2)`` with ``rho = E[g^2]/sigma^2`` is
always optimistic, by an amount set by ``kappa = Var(g^2) / E[g^2]^2``.

Everything is in ``verification.py``; ``experiments/theory`` runs it.
"""

from .verification import Q, exact_error, population_error, simulated_error

__all__ = ["Q", "exact_error", "population_error", "simulated_error"]
