"""LR-DSR: Latent-Regime Deep Symbolic Regression.

Each window of data is generated by one of ``K`` unknown closed-form laws, and
which one is never observed. LR-DSR recovers the laws and the window labels
together, by alternating a symbolic fit per regime with an out-of-fold
reassignment of every window.

``lrdsr.core``
    The algorithm, dataset-agnostic: ``model.py`` (the alternating loop),
    ``backends.py`` (symbolic-regression engines), ``losses.py`` (the
    assignment cost), ``baselines.py`` (geometric baselines), ``evaluation.py``.
``lrdsr.theory``
    The detection theory: exact window-assignment error, the kappa
    correction, the K-ary sandwich, the efficiency of a robust loss, and the
    delay of sequential (real-time) detection.
``lrdsr.viz``
    Plotting for any fit: windows, laws, mechanism space, costs, learning
    curves, streams, and a live animation of online clustering.

The experiments that produce the paper live outside the package, in
``experiments/``.
"""

from .core.backends import FastSymbolicRegressor, make_symbolic_regressor
from .core.model import DCSRResult, GroupedDCSR, RowDCSR
from .core.online import CusumSegmenter, OnlineLRDSR
from .core.soft import SoftLRDSR

__version__ = "1.0.0"

__all__ = [
    "CusumSegmenter",
    "DCSRResult",
    "FastSymbolicRegressor",
    "GroupedDCSR",
    "OnlineLRDSR",
    "RowDCSR",
    "SoftLRDSR",
    "make_symbolic_regressor",
]
