"""LR-DSR: Latent-Regime Deep Symbolic Regression.

Each window of data is generated by one of ``K`` unknown closed-form laws, and
which one is never observed. LR-DSR recovers the laws and the window labels
together, by alternating a symbolic fit per regime with an out-of-fold
reassignment of every window.

``lrdsr.core``
    The algorithm, dataset-agnostic: ``model.py`` (the alternating loop),
    ``backends.py`` (symbolic-regression engines), ``losses.py`` (the
    assignment cost), ``baselines.py`` (geometric baselines), ``evaluation.py``.
``lrdsr.theory``
    The detection theory: exact window-assignment error, the kappa
    correction, the K-ary sandwich, and ``rho(L)`` for the wet antenna.
``lrdsr.cml``
    The application to commercial microwave links: ITU-R P.838-3 constants and
    the two-slot path / path-plus-antenna fit.

The experiments that produce the paper live outside the package, in
``experiments/``.
"""

from .core.backends import FastSymbolicRegressor, make_symbolic_regressor
from .core.model import DCSRResult, GroupedDCSR, RowDCSR

__version__ = "1.0.0"

__all__ = [
    "DCSRResult",
    "FastSymbolicRegressor",
    "GroupedDCSR",
    "RowDCSR",
    "make_symbolic_regressor",
]
