"""Every number the README quotes, computed from ``results/``.

No number in this project is typed by hand. ``README.md`` is generated by
running this module, so a result that changes changes the prose with it, and
a result that is missing raises here rather than going stale on the page.

    python -m analysis.report            # print the numbers
    python -m analysis.report --write    # regenerate README.md
"""
from __future__ import annotations

import sys

import numpy as np
import pandas as pd

from lrdsr import paths

RES = paths.RESULTS


def _csv(section: str, name: str) -> pd.DataFrame:
    p = RES / section / name
    if not p.exists():
        raise SystemExit(
            f"missing {p.relative_to(paths.ROOT)} -- run `python -m experiments all` first")
    return pd.read_csv(p)


def numbers() -> dict:
    n: dict = {}

    # ---- the ceiling ----------------------------------------------------
    v1 = _csv("theory", "v1_exactness.csv")
    n["v1_cells"] = len(v1)
    v4 = _csv("theory", "v4_common_component.csv")
    n["v4_multiple"] = float(v4.common_multiple.max())
    n["v4_unchanged"] = int(v4.unchanged_within_3sd.sum())
    n["v4_cells"] = len(v4)
    v7 = _csv("theory", "v7_mechanism_space.csv")
    n["v7_cells"] = len(v7)
    vv = _csv("theory", "v7_verdict.csv")
    inside = vv[vv.in_library]
    n["v7_gap_median"] = float(inside.gap_to_oracle_median.iloc[0])
    n["v7_sep_rel_median_pct"] = float(inside.sep_rel_median.iloc[0]) * 100.0

    # ---- does the estimator reach it ------------------------------------
    b = _csv("estimator", "benchmark_summary.csv")
    for col in ("oracle", "lrdsr", "lrdsr_dataspace", "mechanism_kmeans",
                "geometry", "window_features"):
        n[f"bench_{col}"] = float(b[col].mean())
    n["bench_gap"] = float((b.lrdsr - b.oracle).mean())
    n["bench_gap_kmeans"] = float((b.mechanism_kmeans - b.oracle).mean())
    n["bench_cells"] = len(b)

    # ---- what the loop is for -------------------------------------------
    s = _csv("estimator", "loop_value_summary.csv")
    c = s[s.arm == "corruption"].copy()
    c["level"] = c.level.astype(float)
    c = c.sort_values("level")
    n["loop_out_lo"] = float(c.mean_error_out.min())
    n["loop_out_hi"] = float(c.mean_error_out.max())
    n["loop_in_lo"] = float(c.mean_error_in.min())
    n["loop_in_hi"] = float(c.mean_error_in.max())
    n["loop_gain_perfect"] = float(c.mean_gain.iloc[0])
    n["loop_gain_chance"] = float(c.mean_gain.iloc[-1])
    rep = c[c.repairs]
    n["loop_crossover"] = float(rep.level.min()) if len(rep) else np.nan
    i = s[s.arm == "initialiser"].set_index("level")
    for k in ("random", "kmeans", "bgmm", "mechanism"):
        if k in i.index:
            n[f"loop_{k}_in"] = float(i.loc[k, "mean_error_in"])
            n[f"loop_{k}_out"] = float(i.loc[k, "mean_error_out"])

    # ---- what the search does -------------------------------------------
    cx = _csv("estimator", "search_complexity.csv")
    n["search_worst_excess_pct"] = float(
        100 * (cx.bic_excess / cx.floor_rmse).max())
    beta = _csv("estimator", "search_beta.csv")
    g = beta.groupby("beta_complexity").matched_error.mean()
    inert = g[g.index <= 1.0]
    n["beta_inert_lo"], n["beta_inert_hi"] = float(inert.min()), float(inert.max())
    n["beta_max"] = float(g.index.max())
    n["beta_err_at_max"] = float(g.iloc[-1])

    # ---- what declared knowledge is worth -------------------------------
    try:
        k = _csv("functions", "knowledge_gain.csv")
        col = "known_minus_unknown"
        if col in k and "window_len" in k:
            n["ladder_gain_n1"] = float(k[k.window_len == k.window_len.min()][col].max())
            n["ladder_gain_nmax"] = float(
                k[k.window_len == k.window_len.max()][col].abs().max())
            n["ladder_n_max"] = int(k.window_len.max())
    except SystemExit:
        pass
    return n


def main(argv=None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    n = numbers()
    width = max(len(k) for k in n)
    for k, v in n.items():
        print(f"  {k:<{width}}  {v:.4g}" if isinstance(v, float)
              else f"  {k:<{width}}  {v}")
    if "--write" in argv:
        from analysis.readme import write
        write(n)
        print("\nwrote README.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
