"""Every number the README quotes, computed from ``results/``.

No number in this project is typed by hand. ``README.md`` is generated by
running this module, so a result that changes changes the prose with it, and
a result that is missing raises here rather than going stale on the page.

    python -m analysis.report            # print the numbers
    python -m analysis.report --write    # regenerate README.md
"""
from __future__ import annotations

import sys

import numpy as np
import pandas as pd

from lrdsr import paths

RES = paths.RESULTS


def _csv(section: str, name: str) -> pd.DataFrame:
    p = RES / section / name
    if not p.exists():
        raise SystemExit(
            f"missing {p.relative_to(paths.ROOT)} -- run `python -m experiments all` first")
    return pd.read_csv(p)


def numbers() -> dict:
    n: dict = {}

    # ---- the ceiling ----------------------------------------------------
    v1 = _csv("theory", "v1_exactness.csv")
    n["v1_cells"] = len(v1)
    v4 = _csv("theory", "v4_common_component.csv")
    n["v4_multiple"] = float(v4.common_multiple.max())
    n["v4_unchanged"] = int(v4.unchanged_within_3sd.sum())
    n["v4_cells"] = len(v4)
    v7 = _csv("theory", "v7_mechanism_space.csv")
    n["v7_cells"] = len(v7)
    vv = _csv("theory", "v7_verdict.csv")
    inside = vv[vv.in_library]
    n["v7_gap_median"] = float(inside.gap_to_oracle_median.iloc[0])
    n["v7_sep_rel_median_pct"] = float(inside.sep_rel_median.iloc[0]) * 100.0

    # ---- does the estimator reach it ------------------------------------
    b = _csv("estimator", "benchmark_summary.csv")
    for col in ("oracle", "lrdsr", "lrdsr_dataspace", "mechanism_kmeans",
                "geometry", "window_features"):
        n[f"bench_{col}"] = float(b[col].mean())
    n["bench_gap"] = float((b.lrdsr - b.oracle).mean())
    n["bench_gap_kmeans"] = float((b.mechanism_kmeans - b.oracle).mean())
    n["bench_cells"] = len(b)

    # ---- what the loop is for -------------------------------------------
    s = _csv("estimator", "loop_value_summary.csv")
    c = s[s.arm == "corruption"].copy()
    c["level"] = c.level.astype(float)
    c = c.sort_values("level")
    n["loop_out_lo"] = float(c.mean_error_out.min())
    n["loop_out_hi"] = float(c.mean_error_out.max())
    n["loop_in_lo"] = float(c.mean_error_in.min())
    n["loop_in_hi"] = float(c.mean_error_in.max())
    n["loop_gain_perfect"] = float(c.mean_gain.iloc[0])
    n["loop_gain_chance"] = float(c.mean_gain.iloc[-1])
    rep = c[c.repairs]
    n["loop_crossover"] = float(rep.level.min()) if len(rep) else np.nan
    i = s[s.arm == "initialiser"].set_index("level")
    for k in ("random", "kmeans", "bgmm", "mechanism"):
        if k in i.index:
            n[f"loop_{k}_in"] = float(i.loc[k, "mean_error_in"])
            n[f"loop_{k}_out"] = float(i.loc[k, "mean_error_out"])

    # ---- what the search does -------------------------------------------
    cx = _csv("estimator", "search_complexity.csv")
    n["search_worst_excess_pct"] = float(
        100 * (cx.bic_excess / cx.floor_rmse).max())
    beta = _csv("estimator", "search_beta.csv")
    g = beta.groupby("beta_complexity").matched_error.mean()
    flat = g[g <= g.min() + 1e-12]
    n["beta_inert_lo"] = float(g.min())
    n["beta_plateau_max"] = float(flat.index.max())
    bite = g[g.index > flat.index.max()]
    n["beta_bite"] = float(bite.index.min())
    n["beta_err_bite"] = float(bite.iloc[0])
    n["beta_default"] = 0.002
    n["beta_max"] = float(g.index.max())
    n["beta_err_at_max"] = float(g.iloc[-1])

    # ---- what declared knowledge is worth -------------------------------
    try:
        k = _csv("functions", "knowledge_gain.csv")
        col = "known_minus_unknown"
        if col in k and "window_len" in k:
            n["ladder_gain_n1"] = float(k[k.window_len == k.window_len.min()][col].max())
            n["ladder_gain_nmax"] = float(
                k[k.window_len == k.window_len.max()][col].abs().max())
            n["ladder_n_max"] = int(k.window_len.max())
    except SystemExit:
        pass

    n.update(problems_numbers())
    n.update(losses_numbers())
    n.update(online_numbers())
    n.update(realdata_numbers())
    n.update(gaps_numbers())
    n.update(kernel_numbers())
    n.update(classify_numbers())
    n.update(partial_numbers())
    n.update(stream_numbers())
    n.update(wind_numbers())
    n.update(repair_numbers())
    return n


def realdata_numbers() -> dict:
    """Bike sharing and I-94 traffic: one window per day, calendar as reference."""
    n: dict = {}
    s = _csv("realdata", "realdata_summary.csv").set_index(["dataset", "method"])
    for ds in ("bike", "traffic"):
        for m, key in (("lrdsr_alpha0", "lrdsr"), ("soft_student_t", "soft_t"),
                       ("soft_fourier", "soft_fourier"), ("mech_kmeans", "mech"),
                       ("raw_profile_kmeans", "profile")):
            n[f"rd_{ds}_{key}_ari"] = float(s.loc[(ds, m), "ARI_mean"])
            n[f"rd_{ds}_{key}_err"] = float(s.loc[(ds, m), "error_mean"])
        geo = s.loc[ds]
        geo = geo[geo.family == "geometry"]
        n[f"rd_{ds}_geom_ari"] = float(geo.ARI_mean.max())
    cov = _csv("realdata", "realdata_coverage.csv")
    for ds in ("bike", "traffic"):
        row = cov[cov.dataset == ds].iloc[0]
        for c in cov.columns:
            if c != "dataset" and np.issubdtype(type(row[c]), np.number):
                n[f"rd_{ds}_cov_{c}"] = float(row[c])
    r = _csv("realdata", "realdata_rho.csv").set_index(["dataset", "basis"])
    for ds in ("bike", "traffic"):
        n[f"rd_{ds}_rho_lib"] = float(r.loc[(ds, "library"), "rho_trace"])
        n[f"rd_{ds}_rho_fourier"] = float(r.loc[(ds, "fourier"), "rho_trace"])
    d = _csv("realdata", "realdata_disagreements.csv")
    for ds in ("bike", "traffic"):
        g = d[d.dataset == ds]
        n[f"rd_{ds}_disagree"] = len(g)
        n[f"rd_{ds}_holiday_working"] = int(((g.day_type == "holiday")
                                             & (g.behaves_like == "working")).sum())
        n[f"rd_{ds}_working_off"] = int(((g.day_type == "working")
                                         & (g.behaves_like == "off")).sum())
    k = _csv("realdata", "realdata_k_selection.csv")
    n["rd_bic_k"] = int(k[k.chosen].K.max())
    n["rd_bic_kmax"] = int(k.K.max())
    o = _csv("realdata", "realdata_online_summary.csv").set_index(["dataset", "novelty_alpha"])
    for ds in ("bike", "traffic"):
        for a, key in ((1e-3, "a3"), (1e-6, "a6")):
            n[f"rd_{ds}_online_acc_{key}"] = float(o.loc[(ds, a), "online_accuracy"])
            n[f"rd_{ds}_online_births_{key}"] = int(o.loc[(ds, a), "births"])
            n[f"rd_{ds}_online_err_{key}"] = 1.0 - n[f"rd_{ds}_online_acc_{key}"]
    n["rd_warmup_days"] = int(o.warmup_days.iloc[0])
    ll = _csv("realdata", "realdata_learned_loss.csv")
    ll = ll[ll.loss == "learned"].set_index("dataset")
    n["rd_bike_nu"] = float(ll.loc["bike", "nu"])
    n["rd_traffic_nu"] = float(ll.loc["traffic", "nu"])
    return n


def losses_numbers() -> dict:
    """V8 (the efficiency formula) and every loss under four noise laws."""
    n: dict = {}
    eff = _csv("losses", "v8_efficiency.csv")
    v = _csv("losses", "v8_verdict.csv")
    smooth = v[v.loss.isin(["huber", "cauchy", "tukey", "student_t"])]
    small = smooth[smooth.gap_bin.isin(["(0.0, 0.1]", "(0.1, 0.25]"])]
    n["v8_small_within"] = int(small.within.sum())
    n["v8_small_cells"] = int(small.cells.sum())
    mid = smooth[smooth.gap_bin == "(0.25, 0.5]"]
    n["v8_mid_within"], n["v8_mid_cells"] = int(mid.within.sum()), int(mid.cells.sum())
    big = smooth[smooth.gap_bin == "(0.5, inf]"]
    n["v8_big_share"] = float(big.within.sum() / big.cells.sum())
    e = eff.drop_duplicates(["loss", "noise"]).set_index(["noise", "loss"])["eta"]
    for noise in ("gaussian", "student_t3", "contaminated_10"):
        for loss in ("squared", "huber", "cauchy", "lrt"):
            if (noise, loss) in e.index:
                n[f"eta_{noise}_{loss}"] = float(e.loc[(noise, loss)])
    s = _csv("losses", "loss_estimator_summary.csv").set_index(["noise", "arm"])
    for noise in ("gaussian", "laplace", "student_t3", "contaminated_10"):
        for arm in ("oracle_lrt", "oracle_squared", "hard_learned", "hard_squared",
                    "hard_huber", "soft_gaussian", "soft_student_t"):
            if (noise, arm) in s.index:
                n[f"le_{noise}_{arm}"] = float(s.loc[(noise, arm), "mean_error"])
    hd = _csv("losses", "loss_huber_delta_summary.csv")
    hd = hd.set_index(["noise", "delta"]).matched_error
    for noise in ("gaussian", "laplace", "student_t3"):
        n[f"hd_{noise}_old"] = float(hd.loc[(noise, 1.0)])     # ~ the former default
        n[f"hd_{noise}_new"] = float(hd.loc[(noise, 1.345)])
    n["hd_gaussian_squared"] = float(hd.loc[("gaussian", 100.0)])
    learned = s.xs("hard_learned", level="arm")
    n["le_learned_worst_excess"] = float(learned.excess_over_lrt.max())
    tr = _csv("losses", "loss_learning_trace.csv")
    last = tr.sort_values("iteration").groupby(["noise", "seed", "method", "regime"]).tail(1)
    t3 = last[(last.noise == "student_t3") & last.nu.notna()]
    n["nu_t3_hard"] = float(t3[t3.method == "hard_learned"].nu.median())
    n["nu_t3_soft"] = float(t3[t3.method == "soft_student_t"].nu.median())
    return n


def online_numbers() -> dict:
    """V9 (sequential detection) and the real-time streams."""
    n: dict = {}
    v = _csv("online", "v9_verdict.csv").iloc[0]
    n["v9_cells"] = int(v.delay_cells)
    n["v9_delay_first_med"] = float(100 * v.delay_median_abs_rel_err_first_order)
    n["v9_delay_tilted_med"] = float(100 * v.delay_median_abs_rel_err_tilted)
    n["v9_delay_tilted_max"] = float(100 * v.delay_max_abs_rel_err_tilted)
    n["v9_arl_bound_ok"] = int(v.arl_cells_above_lorden_bound)
    n["v9_arl_cells"] = int(v.arl_cells)
    n["v9_arl_tilted_med"] = float(100 * v.arl_median_abs_rel_err_tilted)
    st = _csv("online", "stream_stationary_summary.csv").set_index(["rho", "method"])
    for rho in (0.1, 0.25, 1.0):
        for m in ("oracle", "batch_soft", "batch_lrdsr", "online_history160", "online",
                  "online_frozen"):
            n[f"st_{m}_r{round(100 * rho):03d}"] = float(st.loc[(rho, m), "mean_error"])
    b = _csv("online", "stream_birth_summary.csv")
    n["birth_false"] = float(b[b.stream == "control"].mean_false_births.max())
    n["birth_control_runs"] = len(b[b.stream == "control"])
    good = b[(b.stream == "newcomer") & (b.predicted_power >= 0.48)]
    n["birth_good_frac"] = float(good.frac_born.min())
    n["birth_delay_lo"] = float(good.mean_birth_delay_newcomer_windows.min())
    n["birth_delay_hi"] = float(good.mean_birth_delay_newcomer_windows.max())
    n["birth_err_after_hi"] = float(good.mean_error_after_birth.max())
    d = _csv("online", "stream_drift_summary.csv").set_index("arm")
    for arm, key in (("frozen", "frozen"), ("lambda=1", "l100"), ("lambda=0.98", "l098"),
                     ("lambda=0.95", "l095")):
        n[f"drift_{key}"] = float(d.loc[arm, "error"])
    lat = _csv("online", "stream_latency.csv")
    w = lat[lat.estimator == "OnlineLRDSR.partial_fit"]
    n["lat_lo_us"], n["lat_hi_us"] = float(w.median_us.min()), float(w.median_us.max())
    n["lat_rate_lo"] = float(w.windows_per_s.min())
    c = _csv("online", "stream_cusum_summary.csv").set_index(["rho", "laws", "h"])
    n["cusum_acc_learned"] = float(c.loc[(1.0, "learned_laws", 5.0), "accuracy"])
    n["cusum_acc_true"] = float(c.loc[(1.0, "true_laws", 5.0), "accuracy"])
    n["cusum_delay_learned"] = float(c.loc[(1.0, "learned_laws", 5.0), "mean_delay"])
    n["cusum_delay_pred"] = float(c.loc[(1.0, "learned_laws", 5.0),
                                        "predicted_delay_first_order"])
    return n


def problems_numbers() -> dict:
    """The problem zoo: gap to the oracle per method, and where it fails."""
    n: dict = {}
    s = _csv("problems", "problems_summary.csv")
    cat = _csv("problems", "problems_catalog.csv")
    n["zoo_problems"] = int(s.problem.nunique())
    n["zoo_cells"] = len(s)
    for m in ("lrdsr", "soft_em", "mechanism_kmeans", "profile_kmeans", "geometry"):
        n[f"zoo_gap_{m}"] = float(s[f"{m}_gap"].mean())
    n["zoo_within_lrdsr"] = int((s.lrdsr_gap <= 0.02).sum())
    n["zoo_within_soft"] = int((s.soft_em_gap <= 0.02).sum())
    # the failure: the problem whose gap the library misses the most
    worst = cat.sort_values("gap_outside_library").iloc[-1]
    n["zoo_worst"] = str(worst.problem)
    n["zoo_worst_outside_pct"] = float(100 * worst.gap_outside_library)
    w = s[s.problem == worst.problem].groupby("problem").mean(numeric_only=True).iloc[0]
    n["zoo_worst_gap_lrdsr"] = float(w.lrdsr_gap)
    n["zoo_worst_gap_soft"] = float(w.soft_em_gap)
    n["zoo_worst_gap_mech"] = float(w.mechanism_kmeans_gap)
    rest = s[s.problem != worst.problem]
    n["zoo_rest_gap_lrdsr"] = float(rest.lrdsr_gap.mean())
    n["zoo_rest_gap_soft"] = float(rest.soft_em_gap.mean())
    # out-of-library laws whose GAP the library still spans
    outlib = cat[(~cat.in_library) & (cat.gap_outside_library < 0.01)]
    n["zoo_outlib_n"] = len(outlib)
    n["zoo_outlib_gap_lrdsr"] = float(
        s[s.problem.isin(outlib.problem)].lrdsr_gap.mean())
    return n


def gaps_numbers() -> dict:
    """The I-94 days with sensor gaps: laws at the observed hours vs imputation."""
    n: dict = {}
    cov = _csv("realdata", "realdata_gaps_coverage.csv").iloc[0]
    n["gap_days"] = int(cov.partial)
    n["gap_complete"] = int(cov.complete)
    n["gap_min_hours"] = int(cov.min_hours)
    s = _csv("realdata", "realdata_gaps_summary.csv")
    a = s[s.arm == "assign"].set_index(["hours_bin", "route"])
    for b, key in (("all", "all"), ("(5, 11]", "lo"), ("(11, 17]", "mid")):
        for r, rk in (("law", "law"), ("profile_linear", "lin"), ("profile_mean", "mean")):
            n[f"gap_{key}_{rk}"] = float(a.loc[(b, r), "accuracy"])
        n[f"gap_{key}_n"] = int(a.loc[(b, "law"), "n_days"])
    sup = s[(s.arm == "supervised") & (s.hours_bin == "all")].set_index("route")
    n["gap_sup_law"] = float(sup.loc["law", "accuracy"])
    n["gap_sup_mean"] = float(sup.loc["profile_mean", "accuracy"])
    t = _csv("realdata", "realdata_gaps_transplant.csv").set_index(["hours_bin", "route"])
    for r, rk in (("law", "law"), ("profile_linear", "lin"), ("profile_mean", "mean")):
        n[f"tp_lo_{rk}"] = float(t.loc[("(5, 11]", r), "agrees_with_full_day"])
        n[f"tp_mid_{rk}"] = float(t.loc[("(11, 17]", r), "agrees_with_full_day"])
    n["tp_lo_n"] = int(t.loc[("(5, 11]", "law"), "n"])
    return n


def kernel_numbers() -> dict:
    """The kernel basis on the problem zoo."""
    n: dict = {}
    z = _csv("kernel", "kernel_zoo.csv")
    g = z.groupby("method").gap_to_oracle.mean()
    for m in ("mech_library", "mech_kernel", "soft_em_library", "soft_em_kernel",
              "profile_kmeans"):
        n[f"k_gap_{m}"] = float(g[m])
    hf = z[z.problem == "high_frequency"].groupby("method").gap_to_oracle.mean()
    for m in ("mech_library", "mech_kernel", "soft_em_library", "soft_em_kernel"):
        n[f"k_hf_{m}"] = float(hf[m])
    per = z.groupby(["problem", "method"]).gap_to_oracle.mean().unstack()
    n["k_problems"] = len(per)
    n["k_soft_better"] = int((per.soft_em_kernel < per.soft_em_library - 1e-9).sum())
    n["k_soft_worse_002"] = int((per.soft_em_kernel > per.soft_em_library + 0.002).sum())
    cat = _csv("kernel", "kernel_gap_catalog.csv").set_index("problem")
    n["k_hf_out_lib"] = float(100 * cat.loc["high_frequency", "gap_outside_library"])
    n["k_hf_out_16"] = float(100 * cat.loc["high_frequency", "gap_outside_nystrom_16"])
    tune = _csv("kernel", "kernel_rules_tune.csv")
    rep = _csv("kernel", "kernel_rules.csv")
    for r in ("loo_min", "loo_1se", "snr", "snr_1se", "snr_smooth"):
        n[f"k_tune_{r}"] = float(tune[f"{r}_error"].mean())
        n[f"k_rep_{r}"] = float(rep[f"{r}_error"].mean())
    n["k_tune_best"] = float(tune.best_rank_error.mean())
    n["k_rule"] = str(rep.rule_chosen_on_tune.iloc[0])
    n["k_rep_chosen"] = float(rep[f"{n['k_rule']}_error"].mean())
    n["k_rep_best"] = float(rep.best_rank_error.mean())
    h = rep[rep.problem == "high_frequency"].groupby("rho")
    n["k_hf_loo_r025"] = float(h.loo_min_error.mean()[0.25])
    n["k_hf_snr_r025"] = float(h[f"{n['k_rule']}_error"].mean()[0.25])
    n["k_hf_snr_r010"] = float(h[f"{n['k_rule']}_error"].mean()[0.1])
    n["k_hf_best_r010"] = float(h.best_rank_error.mean()[0.1])
    n["k_hf_cut_mech"] = 100 * (1 - n["k_hf_mech_kernel"] / n["k_hf_mech_library"])
    n["k_hf_cut_soft"] = 100 * (1 - n["k_hf_soft_em_kernel"] / n["k_hf_soft_em_library"])
    return n


def classify_numbers() -> dict:
    """V10, and the UCR benchmark, few-shot, irregular and clustering arms."""
    n: dict = {}
    v = _csv("classify", "v10_learning_curve.csv")
    f = v[v.design == "fixed"]
    r = v[v.design == "random"]
    n["v10_cells"] = len(f)
    n["v10_fixed_in"] = int(f.in_band_exact.sum())
    n["v10_fixed_first_in"] = int(f.in_band_first_order.sum())
    small = r[r.p_over_mn <= 0.05]
    n["v10_rand_small_in"] = int(small.in_band_applicable.sum())
    n["v10_rand_small_n"] = len(small)
    big = r[r.p_over_mn > 0.2]
    n["v10_rand_big_in"] = int(big.in_band_applicable.sum())
    n["v10_rand_big_n"] = len(big)
    n["v10_rand_uncorr_in"] = int(r.in_band_exact.sum())
    c = f[(f.D2 == 9) & (f.m == 1)].set_index("p")
    n["v10_p3_m1"] = float(c.loc[3, "simulated"])
    n["v10_p31_m1"] = float(c.loc[31, "simulated"])
    n["v10_ceiling9"] = float(c.ceiling.iloc[0])
    if not (RES / "classify" / "ucr_benchmark.csv").exists():
        return n
    n.update(_ucr_numbers())
    return n


def _ucr_numbers() -> dict:
    """The UCR arms: pre-declared pairs, best-of rows, few-shot, irregular, clustering."""
    n: dict = {}
    b = _csv("classify", "ucr_benchmark.csv")
    piv = b.pivot_table(index=["group", "dataset"], columns="method", values="error")
    piv["best_law"] = piv[["law_cosine", "law_nystrom"]].min(axis=1)
    piv["best_raw"] = piv[[c for c in piv.columns if c.startswith("raw_")]].min(axis=1)
    n["ucr_n"] = len(piv)
    for g in ("daily", "shape"):
        q = piv.loc[g]
        n[f"ucr_{g}_n"] = len(q)
        for a, c, key in (("law_cosine", "raw_1nn_ed", "law_vs_1nn"),
                          ("law_cosine", "raw_centroid", "law_vs_cen"),
                          ("mech_logistic", "raw_logistic", "mlog"),
                          ("mech_svm", "raw_svm", "msvm"),
                          ("best_law", "best_raw", "best")):
            n[f"ucr_{g}_{key}_wins"] = int((q[a] <= q[c] + 1e-9).sum())
            n[f"ucr_{g}_{key}_a"] = float(q[a].mean())
            n[f"ucr_{g}_{key}_b"] = float(q[c].mean())
        n[f"ucr_{g}_symbolic"] = float(q["law_symbolic"].mean())
        n[f"ucr_{g}_dtw"] = float(q["published_1nn_dtw"].mean())
        n[f"ucr_{g}_law_le_dtw"] = int((q.best_law <= q.published_1nn_dtw + 1e-9).sum())
    for name in ("SyntheticControl", "TwoPatterns", "DodgerLoopGame", "Trace"):
        r = piv.xs(name, level=1).iloc[0]
        for col, key in (("law_cosine", "law"), ("raw_1nn_ed", "ed"),
                         ("published_1nn_dtw", "dtw"), ("best_raw", "raw")):
            n[f"ucr_{name}_{key}"] = float(r[col])
    f = _csv("classify", "ucr_fewshot.csv")
    fm = f.groupby(["group", "m", "method"]).error.mean()
    for g in ("daily", "shape"):
        for m in (1, 10):
            for meth, key in (("law_Lall", "lall"), ("law_L1", "l1"),
                              ("raw_1nn_ed", "nn"), ("raw_centroid", "cen")):
                n[f"fs_{g}_m{m}_{key}"] = float(fm.loc[(g, m, meth)])
    per = f.groupby(["group", "m", "dataset", "method"]).error.mean().unstack()
    n["fs_l1_beats_cen"] = int((per.law_L1 < per.raw_centroid - 1e-9).sum())
    n["fs_cells"] = len(per)
    if (RES / "classify" / "ucr_irregular.csv").exists():
        r = _csv("classify", "ucr_irregular.csv")
        rm = r.groupby(["group", "keep", "method"]).error.mean()
        for g in ("daily", "shape"):
            for k, kk in ((1.0, "100"), (0.25, "25"), (0.1, "10")):
                for meth, key in (("law_cosine", "law"), ("raw_1nn_ed", "nn"),
                                  ("raw_centroid", "cen"),
                                  ("mech_logistic_solve", "msolve"),
                                  ("mech_logistic_project", "mproj")):
                    n[f"irr_{g}_{kk}_{key}"] = float(rm.loc[(g, k, meth)])
        pr = r[r.keep == 0.1].groupby(["dataset", "method"]).error.mean().unstack()
        n["irr10_law_wins"] = int((pr.law_cosine <= pr.raw_1nn_ed + 1e-9).sum())
        n["irr10_n"] = len(pr)
    if (RES / "classify" / "ucr_clustering.csv").exists():
        c = _csv("classify", "ucr_clustering.csv")
        cm = c.groupby(["group", "keep", "method"]).ARI.mean()
        for g in ("daily", "shape"):
            for k, kk in ((1.0, "100"), (0.25, "25")):
                for meth, key in (("mech_kmeans_project", "mproj"),
                                  ("mech_kmeans_solve", "msolve"),
                                  ("raw_kmeans", "raw")):
                    n[f"cl_{g}_{kk}_{key}"] = float(cm.loc[(g, k, meth)])
            n[f"cl_{g}_100_soft"] = float(cm.loc[(g, 1.0, "soft_em_cosine")])
    return n


def partial_numbers() -> dict:
    """V11 on real days: which hours, calibration, early decision."""
    n: dict = {}
    rk = _csv("realdata", "realdata_partial_ranking.csv").set_index(["dataset", "block_hours"])
    n["v11_rho_min"] = float(rk.spearman.min())
    n["v11_rho_max"] = float(rk.spearman.max())
    n["v11_worst_hits"] = int((rk.worst_start_predicted == rk.worst_start_observed).sum())
    n["v11_worst_n"] = len(rk)
    n["v11_tr12_max"] = float(rk.loc[("traffic", 12), "max_observed"])
    pre = _csv("realdata", "realdata_partial_prefix.csv")
    pre["hours"] = pre["mask_label"].astype(int)
    p = pre.set_index(["dataset", "hours"])
    for ds, h in (("traffic", 4), ("traffic", 5), ("bike", 5), ("bike", 6)):
        n[f"v11_{ds}_{h}h_pred"] = float(p.loc[(ds, h), "pred_decided_right"])
        n[f"v11_{ds}_{h}h_obs"] = float(p.loc[(ds, h), "decided_right"])
    cal = _csv("realdata", "realdata_partial_calibration.csv")
    blk = cal[(cal.dataset == "traffic") & (cal.family == "block")].set_index("bin")
    n["v11_cal_mid_pred"] = float(blk.loc["(0.03, 0.1]", "predicted"])
    n["v11_cal_mid_obs"] = float(blk.loc["(0.03, 0.1]", "observed"])
    n["v11_cal_low_pred"] = float(blk.loc["(-0.001, 0.002]", "predicted"])
    n["v11_cal_low_obs"] = float(blk.loc["(-0.001, 0.002]", "observed"])
    return n


def stream_numbers() -> dict:
    """Part C: the kernel birth stream and the full I-94 stream."""
    n: dict = {}
    kb = _csv("online", "online_ragged_kernel_birth.csv")
    new = kb[~kb.control]
    g = new.groupby(["basis", "rho"]).births.apply(lambda s: int((s > 0).sum()))
    for b in ("kernel", "library"):
        for r in (0.5, 1.0, 2.0):
            n[f"cb_{b}_{int(r * 10):02d}"] = int(g.loc[(b, r)])
    n["cb_seeds"] = int(new.seed.nunique())
    n["cb_kernel_delay"] = float(new[(new.basis == "kernel") & (new.rho >= 1)].birth_delay.mean())
    n["cb_kernel_err"] = float(new[(new.basis == "kernel") & (new.rho >= 1)]
                               .error_after_birth.mean())
    n["cb_false"] = int(kb[kb.control].births.sum())
    n["cb_power_10"] = float(new[new.rho == 1.0].predicted_power.iloc[0])
    t = _csv("online", "online_ragged_traffic_summary.csv").set_index(["arm", "days"])
    n["st_all_n"] = int(t.loc[("all_days", "all"), "n"])
    n["st_all_acc"] = float(t.loc[("all_days", "all"), "accuracy"])
    n["st_partial_n"] = int(t.loc[("all_days", "partial"), "n"])
    n["st_partial_acc"] = float(t.loc[("all_days", "partial"), "accuracy"])
    n["st_complete_acc"] = float(t.loc[("all_days", "complete"), "accuracy"])
    n["st_only_acc"] = float(t.loc[("complete_only", "all"), "accuracy"])
    return n


def wind_numbers() -> dict:
    """Part D: Kelmarsh power curves."""
    n: dict = {}
    cov = _csv("wind", "wind_coverage.csv").iloc[0]
    n["w_blocks"] = int(cov.blocks)
    n["w_first"] = str(cov.first_block)[:7]
    n["w_last"] = str(cov.last_block)[:7]
    n["w_cov_med"] = float(cov.median_bins_covered)
    n["w_cov_tot"] = int(cov.bins_total)
    n["w_sd_missing"] = float(cov.ws_sd_missing)
    n["w_night_dep"] = float(cov.night_day_max_departure)
    n["w_ti_ratio"] = float(cov.turbulence_ratio_5ms)
    n["w_wake_ratio"] = float(cov.waked_0) / float(cov.waked_1)
    t = _csv("wind", "wind_transfer.csv")
    m = t.groupby(["proxy", "method"]).balanced_error.mean()
    c = t.groupby("proxy").ceiling_v1.mean()
    for p in ("cold", "waked", "night"):
        for meth in ("law", "mech_logistic", "bins_logistic", "bins_1nn", "bins_centroid"):
            n[f"w_{p}_{meth}"] = float(m.loc[(p, meth)])
        n[f"w_{p}_bins_best"] = float(min(m.loc[(p, k)] for k in
                                          ("bins_logistic", "bins_1nn", "bins_centroid")))
        n[f"w_{p}_ceiling"] = float(c.loc[p])
    ct = _csv("wind", "wind_coverage_terciles.csv")
    cm = ct.groupby(["proxy", "coverage", "method"]).balanced_error.mean()
    for p in ("cold", "waked"):
        for tr in ("narrow", "wide"):
            best = min(cm.loc[(p, tr, "bins_logistic")], cm.loc[(p, tr, "bins_1nn")])
            n[f"w_{p}_{tr}_edge"] = float(best - cm.loc[(p, tr, "law")])
    ph = _csv("wind", "wind_physics.csv")
    n["w_density"] = float(ph.density_ratio.iloc[0])
    n["w_Tc"], n["w_Tw"] = float(ph.T_cold_C.iloc[0]), float(ph.T_warm_C.iloc[0])
    n["w_ratio_lo"] = float(ph.bins_ratio.iloc[0])
    n["w_ratio_hi"] = float(ph.bins_ratio.iloc[-1])
    n["w_ws_lo"], n["w_ws_hi"] = float(ph.ws.iloc[0]), float(ph.ws.iloc[-1])
    n["w_uniform_dev"] = float((ph.law_uniform_ratio - ph.bins_ratio).abs().max())
    n["w_quantile_dev"] = float((ph.law_ratio - ph.bins_ratio).abs().max())
    cl = _csv("wind", "wind_clusters.csv").groupby("method").mean(numeric_only=True)
    n["w_cl_mech_maxproxy"] = float(cl.loc["mech_kmeans", ["ARI_cold", "ARI_waked",
                                                          "ARI_night", "ARI_winter"]].abs().max())
    n["w_cl_bins_calm"] = float(cl.loc["bins_kmeans", "ARI_calm"])
    on = _csv("wind", "wind_online.csv")
    births = on[on.regime >= 0]
    n["w_births"] = len(births)
    n["w_births_xmas"] = int(births.born_at.str.startswith(("2016-12-24", "2016-12-25",
                                                           "2016-12-26")).sum())
    xmas = births[births.born_at.str.startswith(("2016-12-24", "2016-12-25", "2016-12-26"))]
    n["w_births_xmas_turbines"] = int(xmas.turbine.nunique())
    n["w_xmas_top3"] = int((xmas.ws_percentile >= 0.97).sum())
    n["w_xmas_min_pct"] = float(100 * xmas.ws_percentile.min())
    return n


def repair_numbers() -> dict:
    """Part B: the warp, the stack, the design-exact V10."""
    n: dict = {}
    f = _csv("classify", "ucr_fixes.csv")
    b = _csv("classify", "ucr_benchmark.csv")
    P = b.pivot_table(index=["group", "dataset"], columns="method", values="error")
    F = f.pivot_table(index=["group", "dataset"], columns="method", values="error")
    D = P[["law_cosine", "published_1nn_dtw"]].join(F)
    D["best_raw"] = P[[c for c in P.columns if c.startswith("raw_")]].min(axis=1)
    for g in ("daily", "shape"):
        q = D.loc[g]
        for col, key in (("law_cosine", "law"), ("law_shift", "shift"), ("law_stack", "stack"),
                         ("best_raw", "raw"), ("published_1nn_dtw", "dtw")):
            n[f"rp_{g}_{key}"] = float(q[col].mean())
        n[f"rp_{g}_shift_better"] = int((q.law_shift < q.law_cosine - 1e-9).sum())
        n[f"rp_{g}_shift_worse"] = int((q.law_shift > q.law_cosine + 1e-9).sum())
        n[f"rp_{g}_stack_beats_raw"] = int((q.law_stack <= q.best_raw + 1e-9).sum())
    for name in ("Trace", "GunPoint", "TwoPatterns", "CBF", "ECG200", "FaceFour", "Lightning7"):
        r = D.xs(name, level=1).iloc[0]
        for col, key in (("law_cosine", "law"), ("law_shift", "shift"), ("law_stack", "stack"),
                         ("published_1nn_dtw", "dtw")):
            n[f"rp_{name}_{key}"] = float(r[col])
    d = _csv("classify", "v10_design_exact.csv")
    n["v10x_in"] = int(d.in_band_design_exact.sum())
    n["v10x_n"] = len(d)
    big = d[d.p_over_mn > 0.2]
    n["v10x_big_in"] = int(big.in_band_design_exact.sum())
    n["v10x_big_n"] = len(big)
    return n


def main(argv=None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    n = numbers()
    width = max(len(k) for k in n)
    for k, v in n.items():
        print(f"  {k:<{width}}  {v:.4g}" if isinstance(v, float)
              else f"  {k:<{width}}  {v}")
    if "--write" in argv:
        from analysis import results
        from analysis.readme import write
        write(n)
        results.write(n)
        print("\nwrote README.md, RESULTS.md and docs/figures/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
